version: "3.8"
services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=172.187.176.69 # 您的内网 IP 地址
      - PASSWORD_HASH=$$2a$$12$$31H.ZEl74tEF98shuIWWxe2PTsljr3vEMRfU7HL8dPvNJTImcUgRq
      - WG_PORT=20000 # WireGuard 端口
      - WG_DEFAULT_DNS=1.1.1.1 # 可选：设置默认 DNS 服务器
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0 # 可选：允许所有 IP 地址
      # - WG_MTU=1420 # 可选：设置 MTU 大小
    volumes:
      - ./wg-data:/etc/wireguard # 将 WireGuard 数据持久化到本地目录
    ports:
      - "20000:20000/udp" # WireGuard 端口
      - "443:51821/tcp" # 后台端口
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.disable_ipv6=0 # 如果您使用 IPv6，请删除此行
    restart: unless-stopped
